//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantLog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public int OrderID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
