//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantLog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInformation
    {
        public int ID { get; set; }
        public System.DateTime Born { get; set; }
        public string Tel { get; set; }
        public string PasspSeries { get; set; }
        public string PasspNumber { get; set; }
        public int PostsID { get; set; }
    
        public virtual Authorization Authorization { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Posts Posts { get; set; }
    }
}
